---
- name: Query Isilon Status
  hosts: isilon1
  vars:
   isilon_cmd: "isi status"
   LogDir: "/tmp"
   DateTimeStamp: "{{ansible_date_time.date}}.{{ansible_date_time.time}}"

  gather_facts: no

  tasks:
   - name: connect to "{{ansible_host}}" via SSH and issue "isi status"
     shell: "{{isilon_cmd}}"
     register: output
     changed_when: "'[  OK ]' not in output.stdout"

   - debug:
       var: output
